### ISSUE TITLE
Enable Source Link for easier debugging

### ISSUE THREAD

**Issue by MagicAndre1981** [LorenzCK/WindowsFormsAero#6]
### Expected  behavior

Press F11 to step into code and debug the code

### Actual behavior

because no source info are found in the provided PDB, debugger steps over

### Solution: 

[enable Source Link](https://github.com/dotnet/sourcelink#using-sourcelink) to [fetch the source from github](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#source-link-file-specification) during debugging to be able to step into the code.

**Comment by MagicAndre1981** [comment]
@LorenzCK any chance for new nuget package?

**Comment by withrenren2thealt** [comment]
WHERE IS THE APP
